/**
 * File & folder icons using the Seti icon font (MIT, by Jesse Weed).
 * The seti.woff font is bundled in src/renderer/assets/seti.woff.
 */
import setiWoff from '../assets/seti.woff'

// ---------------------------------------------------------------------------
// Font-face injection (runs once on import)
// ---------------------------------------------------------------------------
const FONT_ID = 'seti-icons'
let fontInjected = false

function ensureFont(): void {
  if (fontInjected || typeof document === 'undefined') return
  fontInjected = true
  const style = document.createElement('style')
  style.textContent = `
    @font-face {
      font-family: "${FONT_ID}";
      src: url("${setiWoff}") format("woff");
      font-weight: normal;
      font-style: normal;
      font-display: block;
    }
  `
  document.head.appendChild(style)
}

// ---------------------------------------------------------------------------
// Icon definitions  { ch: fontCharacter, color: hex }
// Extracted from VS Code's Seti theme (jesseweed/seti-ui, MIT license)
// ---------------------------------------------------------------------------
interface IconDef {
  ch: string
  color: string
}

const D: Record<string, IconDef> = {
  _default: { ch: '\uE023', color: '#d4d7d6' },
  _R: { ch: '\uE001', color: '#519aba' },
  _argdown: { ch: '\uE003', color: '#519aba' },
  _asm: { ch: '\uE004', color: '#cc3e44' },
  _audio: { ch: '\uE005', color: '#a074c4' },
  _babel: { ch: '\uE006', color: '#cbcb41' },
  _bazel: { ch: '\uE007', color: '#8dc149' },
  _bazel_1: { ch: '\uE007', color: '#4d5a5e' },
  _bicep: { ch: '\uE008', color: '#519aba' },
  _bower: { ch: '\uE009', color: '#e37933' },
  _bsl: { ch: '\uE00A', color: '#cc3e44' },
  '_c-sharp': { ch: '\uE00B', color: '#519aba' },
  _c: { ch: '\uE00C', color: '#519aba' },
  _c_1: { ch: '\uE00C', color: '#a074c4' },
  _c_2: { ch: '\uE00C', color: '#cbcb41' },
  _cake: { ch: '\uE00D', color: '#cc3e44' },
  _cake_php: { ch: '\uE00E', color: '#cc3e44' },
  _clock: { ch: '\uE012', color: '#519aba' },
  _clock_1: { ch: '\uE012', color: '#6d8086' },
  _clojure: { ch: '\uE013', color: '#8dc149' },
  _clojure_1: { ch: '\uE013', color: '#519aba' },
  '_code-climate': { ch: '\uE014', color: '#8dc149' },
  '_code-search': { ch: '\uE015', color: '#a074c4' },
  _coffee: { ch: '\uE016', color: '#cbcb41' },
  _coldfusion: { ch: '\uE018', color: '#519aba' },
  _config: { ch: '\uE019', color: '#6d8086' },
  _cpp: { ch: '\uE01A', color: '#519aba' },
  _cpp_1: { ch: '\uE01A', color: '#a074c4' },
  _cpp_2: { ch: '\uE01A', color: '#cbcb41' },
  _crystal: { ch: '\uE01B', color: '#d4d7d6' },
  _crystal_embedded: { ch: '\uE01C', color: '#d4d7d6' },
  _css: { ch: '\uE01D', color: '#519aba' },
  _csv: { ch: '\uE01E', color: '#8dc149' },
  _cu: { ch: '\uE01F', color: '#8dc149' },
  _cu_1: { ch: '\uE01F', color: '#a074c4' },
  _d: { ch: '\uE020', color: '#cc3e44' },
  _dart: { ch: '\uE021', color: '#519aba' },
  _db: { ch: '\uE022', color: '#f55385' },
  _db_1: { ch: '\uE022', color: '#519aba' },
  _docker: { ch: '\uE025', color: '#519aba' },
  _docker_1: { ch: '\uE025', color: '#4d5a5e' },
  _docker_2: { ch: '\uE025', color: '#8dc149' },
  _docker_3: { ch: '\uE025', color: '#f55385' },
  _ejs: { ch: '\uE027', color: '#cbcb41' },
  _elixir: { ch: '\uE028', color: '#a074c4' },
  _elixir_script: { ch: '\uE029', color: '#a074c4' },
  _elm: { ch: '\uE02A', color: '#519aba' },
  _eslint: { ch: '\uE02C', color: '#a074c4' },
  _eslint_1: { ch: '\uE02C', color: '#4d5a5e' },
  _ethereum: { ch: '\uE02D', color: '#519aba' },
  '_f-sharp': { ch: '\uE02E', color: '#519aba' },
  _favicon: { ch: '\uE02F', color: '#cbcb41' },
  _firebase: { ch: '\uE030', color: '#e37933' },
  _firefox: { ch: '\uE031', color: '#e37933' },
  _font: { ch: '\uE033', color: '#cc3e44' },
  _git: { ch: '\uE034', color: '#41535b' },
  _github: { ch: '\uE037', color: '#d4d7d6' },
  _gitlab: { ch: '\uE038', color: '#e37933' },
  _go: { ch: '\uE039', color: '#519aba' },
  _go2: { ch: '\uE03A', color: '#519aba' },
  _godot: { ch: '\uE03B', color: '#519aba' },
  _godot_1: { ch: '\uE03B', color: '#cc3e44' },
  _godot_2: { ch: '\uE03B', color: '#cbcb41' },
  _godot_3: { ch: '\uE03B', color: '#a074c4' },
  _gradle: { ch: '\uE03C', color: '#519aba' },
  _grails: { ch: '\uE03D', color: '#8dc149' },
  _graphql: { ch: '\uE03E', color: '#f55385' },
  _grunt: { ch: '\uE03F', color: '#e37933' },
  _gulp: { ch: '\uE040', color: '#cc3e44' },
  _hacklang: { ch: '\uE041', color: '#e37933' },
  _haml: { ch: '\uE042', color: '#cc3e44' },
  _happenings: { ch: '\uE043', color: '#519aba' },
  _haskell: { ch: '\uE044', color: '#a074c4' },
  _haxe: { ch: '\uE045', color: '#e37933' },
  _haxe_1: { ch: '\uE045', color: '#cbcb41' },
  _haxe_2: { ch: '\uE045', color: '#519aba' },
  _haxe_3: { ch: '\uE045', color: '#a074c4' },
  _heroku: { ch: '\uE046', color: '#a074c4' },
  _hex: { ch: '\uE047', color: '#cc3e44' },
  _html: { ch: '\uE048', color: '#519aba' },
  _html_1: { ch: '\uE048', color: '#8dc149' },
  _html_2: { ch: '\uE048', color: '#cbcb41' },
  _html_3: { ch: '\uE048', color: '#e37933' },
  _html_erb: { ch: '\uE049', color: '#cc3e44' },
  _ignored: { ch: '\uE04A', color: '#41535b' },
  _illustrator: { ch: '\uE04B', color: '#cbcb41' },
  _image: { ch: '\uE04C', color: '#a074c4' },
  _info: { ch: '\uE04D', color: '#519aba' },
  _ionic: { ch: '\uE04E', color: '#519aba' },
  _jade: { ch: '\uE04F', color: '#cc3e44' },
  _java: { ch: '\uE050', color: '#cc3e44' },
  _java_1: { ch: '\uE050', color: '#519aba' },
  _javascript: { ch: '\uE051', color: '#cbcb41' },
  _javascript_1: { ch: '\uE051', color: '#e37933' },
  _javascript_2: { ch: '\uE051', color: '#519aba' },
  _jenkins: { ch: '\uE052', color: '#cc3e44' },
  _jinja: { ch: '\uE053', color: '#cc3e44' },
  _json: { ch: '\uE055', color: '#cbcb41' },
  _json_1: { ch: '\uE055', color: '#8dc149' },
  _julia: { ch: '\uE056', color: '#a074c4' },
  _karma: { ch: '\uE057', color: '#8dc149' },
  _kotlin: { ch: '\uE058', color: '#e37933' },
  _less: { ch: '\uE059', color: '#519aba' },
  _license: { ch: '\uE05A', color: '#cbcb41' },
  _license_1: { ch: '\uE05A', color: '#e37933' },
  _license_2: { ch: '\uE05A', color: '#cc3e44' },
  _liquid: { ch: '\uE05B', color: '#8dc149' },
  _livescript: { ch: '\uE05C', color: '#519aba' },
  _lock: { ch: '\uE05D', color: '#8dc149' },
  _lua: { ch: '\uE05E', color: '#519aba' },
  _makefile: { ch: '\uE05F', color: '#e37933' },
  _makefile_1: { ch: '\uE05F', color: '#a074c4' },
  _makefile_2: { ch: '\uE05F', color: '#6d8086' },
  _makefile_3: { ch: '\uE05F', color: '#519aba' },
  _markdown: { ch: '\uE060', color: '#519aba' },
  _maven: { ch: '\uE061', color: '#cc3e44' },
  _mdo: { ch: '\uE062', color: '#cc3e44' },
  _mustache: { ch: '\uE063', color: '#e37933' },
  _nim: { ch: '\uE065', color: '#cbcb41' },
  _notebook: { ch: '\uE066', color: '#519aba' },
  _npm: { ch: '\uE067', color: '#41535b' },
  _npm_1: { ch: '\uE067', color: '#cc3e44' },
  _npm_ignored: { ch: '\uE068', color: '#41535b' },
  _nunjucks: { ch: '\uE069', color: '#8dc149' },
  _ocaml: { ch: '\uE06A', color: '#e37933' },
  _odata: { ch: '\uE06B', color: '#e37933' },
  _pddl: { ch: '\uE06C', color: '#a074c4' },
  _pdf: { ch: '\uE06D', color: '#cc3e44' },
  _perl: { ch: '\uE06E', color: '#519aba' },
  _photoshop: { ch: '\uE06F', color: '#519aba' },
  _php: { ch: '\uE070', color: '#a074c4' },
  _pipeline: { ch: '\uE071', color: '#e37933' },
  _plan: { ch: '\uE072', color: '#8dc149' },
  _platformio: { ch: '\uE073', color: '#e37933' },
  _powershell: { ch: '\uE074', color: '#519aba' },
  _prisma: { ch: '\uE075', color: '#519aba' },
  _prolog: { ch: '\uE077', color: '#e37933' },
  _pug: { ch: '\uE078', color: '#cc3e44' },
  _puppet: { ch: '\uE079', color: '#cbcb41' },
  _purescript: { ch: '\uE07A', color: '#d4d7d6' },
  _python: { ch: '\uE07B', color: '#519aba' },
  _react: { ch: '\uE07D', color: '#519aba' },
  _react_1: { ch: '\uE07D', color: '#e37933' },
  _reasonml: { ch: '\uE07E', color: '#cc3e44' },
  _rescript: { ch: '\uE07F', color: '#cc3e44' },
  _rescript_1: { ch: '\uE07F', color: '#f55385' },
  _rollup: { ch: '\uE080', color: '#cc3e44' },
  _ruby: { ch: '\uE081', color: '#cc3e44' },
  _rust: { ch: '\uE082', color: '#6d8086' },
  _salesforce: { ch: '\uE083', color: '#519aba' },
  _sass: { ch: '\uE084', color: '#f55385' },
  _sbt: { ch: '\uE085', color: '#519aba' },
  _scala: { ch: '\uE086', color: '#cc3e44' },
  _shell: { ch: '\uE089', color: '#8dc149' },
  _slim: { ch: '\uE08A', color: '#e37933' },
  _smarty: { ch: '\uE08B', color: '#cbcb41' },
  _spring: { ch: '\uE08C', color: '#8dc149' },
  _stylelint: { ch: '\uE08D', color: '#d4d7d6' },
  _stylelint_1: { ch: '\uE08D', color: '#4d5a5e' },
  _stylus: { ch: '\uE08E', color: '#8dc149' },
  _sublime: { ch: '\uE08F', color: '#e37933' },
  _svelte: { ch: '\uE090', color: '#cc3e44' },
  _svg: { ch: '\uE091', color: '#a074c4' },
  _svg_1: { ch: '\uE091', color: '#519aba' },
  _swift: { ch: '\uE092', color: '#e37933' },
  _terraform: { ch: '\uE093', color: '#a074c4' },
  _tex: { ch: '\uE094', color: '#519aba' },
  _tex_1: { ch: '\uE094', color: '#cbcb41' },
  _tex_2: { ch: '\uE094', color: '#e37933' },
  _tex_3: { ch: '\uE094', color: '#d4d7d6' },
  _todo: { ch: '\uE096', color: '#6d8086' },
  _tsconfig: { ch: '\uE097', color: '#519aba' },
  _twig: { ch: '\uE098', color: '#8dc149' },
  _typescript: { ch: '\uE099', color: '#519aba' },
  _typescript_1: { ch: '\uE099', color: '#e37933' },
  _vala: { ch: '\uE09A', color: '#6d8086' },
  _video: { ch: '\uE09B', color: '#f55385' },
  _vite: { ch: '\uE09C', color: '#cbcb41' },
  _vue: { ch: '\uE09D', color: '#8dc149' },
  _wasm: { ch: '\uE09E', color: '#a074c4' },
  _wat: { ch: '\uE09F', color: '#a074c4' },
  _webpack: { ch: '\uE0A0', color: '#519aba' },
  _wgt: { ch: '\uE0A1', color: '#519aba' },
  _windows: { ch: '\uE0A2', color: '#519aba' },
  _word: { ch: '\uE0A3', color: '#519aba' },
  _xls: { ch: '\uE0A4', color: '#8dc149' },
  _xml: { ch: '\uE0A5', color: '#e37933' },
  _yarn: { ch: '\uE0A6', color: '#519aba' },
  _yml: { ch: '\uE0A7', color: '#a074c4' },
  _zig: { ch: '\uE0A8', color: '#e37933' },
  _zip: { ch: '\uE0A9', color: '#cc3e44' },
  _zip_1: { ch: '\uE0A9', color: '#6d8086' }
}

// ---------------------------------------------------------------------------
// Extension → icon ID
// ---------------------------------------------------------------------------
const EXT: Record<string, string> = {
  bsl: '_bsl',
  mdo: '_mdo',
  cls: '_salesforce',
  apex: '_salesforce',
  asm: '_asm',
  s: '_asm',
  bicep: '_bicep',
  bzl: '_bazel',
  bazel: '_bazel',
  build: '_bazel',
  workspace: '_bazel',
  bazelignore: '_bazel',
  bazelversion: '_bazel',
  h: '_c_1',
  aspx: '_html',
  ascx: '_html_1',
  asax: '_html_2',
  master: '_html_2',
  hh: '_cpp_1',
  hpp: '_cpp_1',
  hxx: '_cpp_1',
  'h++': '_cpp_1',
  edn: '_clojure_1',
  cfc: '_coldfusion',
  cfm: '_coldfusion',
  litcoffee: '_coffee',
  config: '_config',
  cr: '_crystal',
  ecr: '_crystal_embedded',
  slang: '_crystal_embedded',
  cson: '_json',
  'css.map': '_css',
  sss: '_css',
  csv: '_csv',
  xls: '_xls',
  xlsx: '_xls',
  cuh: '_cu_1',
  hu: '_cu_1',
  cake: '_cake',
  ctp: '_cake_php',
  d: '_d',
  doc: '_word',
  docx: '_word',
  ejs: '_ejs',
  ex: '_elixir',
  exs: '_elixir_script',
  elm: '_elm',
  ico: '_favicon',
  gitconfig: '_git',
  gitkeep: '_git',
  gitattributes: '_git',
  gitmodules: '_git',
  slide: '_go',
  article: '_go',
  gd: '_godot',
  godot: '_godot_1',
  tres: '_godot_2',
  tscn: '_godot_3',
  gradle: '_gradle',
  gsp: '_grails',
  gql: '_graphql',
  graphql: '_graphql',
  graphqls: '_graphql',
  hack: '_hacklang',
  haml: '_haml',
  hs: '_haskell',
  lhs: '_haskell',
  hx: '_haxe',
  hxs: '_haxe_1',
  hxp: '_haxe_2',
  hxml: '_haxe_3',
  jade: '_jade',
  class: '_java_1',
  classpath: '_java',
  'js.map': '_javascript',
  'cjs.map': '_javascript',
  'mjs.map': '_javascript',
  'spec.js': '_javascript_1',
  'spec.cjs': '_javascript_1',
  'spec.mjs': '_javascript_1',
  'test.js': '_javascript_1',
  'test.cjs': '_javascript_1',
  'test.mjs': '_javascript_1',
  es: '_javascript',
  es5: '_javascript',
  es7: '_javascript',
  jinja: '_jinja',
  jinja2: '_jinja',
  kt: '_kotlin',
  kts: '_kotlin',
  liquid: '_liquid',
  ls: '_livescript',
  argdown: '_argdown',
  ad: '_argdown',
  mustache: '_mustache',
  stache: '_mustache',
  nim: '_nim',
  nims: '_nim',
  'github-issues': '_github',
  ipynb: '_notebook',
  njk: '_nunjucks',
  nunjucks: '_nunjucks',
  nunjs: '_nunjucks',
  nunj: '_nunjucks',
  njs: '_nunjucks',
  nj: '_nunjucks',
  'npm-debug.log': '_npm',
  npmignore: '_npm_1',
  npmrc: '_npm_1',
  ml: '_ocaml',
  mli: '_ocaml',
  cmx: '_ocaml',
  cmxa: '_ocaml',
  odata: '_odata',
  'php.inc': '_php',
  pipeline: '_pipeline',
  pddl: '_pddl',
  plan: '_plan',
  happenings: '_happenings',
  prisma: '_prisma',
  pp: '_puppet',
  epp: '_puppet',
  purs: '_purescript',
  'spec.jsx': '_react_1',
  'test.jsx': '_react_1',
  cjsx: '_react',
  'spec.tsx': '_react_1',
  'test.tsx': '_react_1',
  re: '_reasonml',
  res: '_rescript',
  resi: '_rescript_1',
  r: '_R',
  rmd: '_R',
  erb: '_html_erb',
  'erb.html': '_html_erb',
  'html.erb': '_html_erb',
  sass: '_sass',
  springbeans: '_spring',
  slim: '_slim',
  'smarty.tpl': '_smarty',
  tpl: '_smarty',
  sbt: '_sbt',
  scala: '_scala',
  sol: '_ethereum',
  styl: '_stylus',
  svelte: '_svelte',
  soql: '_db_1',
  tf: '_terraform',
  'tf.json': '_terraform',
  tfvars: '_terraform',
  'tfvars.json': '_terraform',
  dtx: '_tex_2',
  ins: '_tex_3',
  toml: '_config',
  twig: '_twig',
  'spec.ts': '_typescript_1',
  'test.ts': '_typescript_1',
  vala: '_vala',
  vapi: '_vala',
  component: '_html_3',
  vue: '_vue',
  wasm: '_wasm',
  wat: '_wat',
  pro: '_prolog',
  zig: '_zig',
  jar: '_zip',
  zip: '_zip_1',
  wgt: '_wgt',
  ai: '_illustrator',
  psd: '_photoshop',
  pdf: '_pdf',
  eot: '_font',
  ttf: '_font',
  woff: '_font',
  woff2: '_font',
  otf: '_font',
  avif: '_image',
  gif: '_image',
  jpg: '_image',
  jpeg: '_image',
  png: '_image',
  pxm: '_image',
  svg: '_svg',
  svgx: '_image',
  tiff: '_image',
  webp: '_image',
  sublime_project: '_sublime',
  sublime_workspace: '_sublime',
  mov: '_video',
  ogv: '_video',
  webm: '_video',
  avi: '_video',
  mpg: '_video',
  mp4: '_video',
  mp3: '_audio',
  ogg: '_audio',
  wav: '_audio',
  flac: '_audio',
  '3ds': '_svg_1',
  '3dm': '_svg_1',
  stl: '_svg_1',
  obj: '_svg_1',
  dae: '_svg_1',
  babelrc: '_babel',
  'babelrc.js': '_babel',
  'babelrc.cjs': '_babel',
  bazelrc: '_bazel_1',
  bowerrc: '_bower',
  dockerignore: '_docker_1',
  'codeclimate.yml': '_code-climate',
  eslintrc: '_eslint',
  'eslintrc.js': '_eslint',
  'eslintrc.cjs': '_eslint',
  'eslintrc.yaml': '_eslint',
  'eslintrc.yml': '_eslint',
  'eslintrc.json': '_eslint',
  eslintignore: '_eslint_1',
  firebaserc: '_firebase',
  'gitlab-ci.yml': '_gitlab',
  jshintrc: '_javascript_2',
  jscsrc: '_javascript_2',
  stylelintrc: '_stylelint',
  'stylelintrc.json': '_stylelint',
  'stylelintrc.yaml': '_stylelint',
  'stylelintrc.yml': '_stylelint',
  'stylelintrc.js': '_stylelint',
  stylelintignore: '_stylelint_1',
  direnv: '_config',
  static: '_config',
  slugignore: '_config',
  tmp: '_clock_1',
  htaccess: '_config',
  key: '_lock',
  cert: '_lock',
  cer: '_lock',
  crt: '_lock',
  pem: '_lock',
  ds_store: '_ignored'
}

// Language IDs (used as fallback for common extensions without compound match)
const LANG_EXT: Record<string, string> = {
  bat: '_windows',
  ts: '_typescript',
  tsx: '_react',
  mts: '_typescript',
  cts: '_typescript',
  js: '_javascript',
  jsx: '_react',
  mjs: '_javascript',
  cjs: '_javascript',
  json: '_json',
  jsonc: '_json',
  json5: '_json',
  jsonl: '_json',
  c: '_c',
  cpp: '_cpp',
  cc: '_cpp',
  cxx: '_cpp',
  cs: '_c-sharp',
  css: '_css',
  scss: '_sass',
  less: '_less',
  postcss: '_css',
  dart: '_dart',
  go: '_go2',
  java: '_java',
  py: '_python',
  rb: '_ruby',
  rs: '_rust',
  swift: '_swift',
  html: '_html_3',
  htm: '_html_3',
  md: '_markdown',
  mdx: '_markdown',
  php: '_php',
  lua: '_lua',
  pl: '_perl',
  pm: '_perl',
  ps1: '_powershell',
  sh: '_shell',
  bash: '_shell',
  zsh: '_shell',
  fish: '_shell',
  sql: '_db',
  xml: '_xml',
  yml: '_yml',
  yaml: '_yml',
  dockerfile: '_docker',
  makefile: '_makefile',
  tex: '_tex',
  latex: '_tex',
  txt: '_default',
  log: '_default',
  ini: '_config',
  cfg: '_config',
  conf: '_config',
  env: '_config'
}

// ---------------------------------------------------------------------------
// Filename → icon ID  (exact match, case-insensitive)
// ---------------------------------------------------------------------------
const NAMES: Record<string, string> = {
  mix: '_hex',
  'karma.conf.js': '_karma',
  'karma.conf.cjs': '_karma',
  'karma.conf.mjs': '_karma',
  'karma.conf.coffee': '_karma',
  'readme.md': '_info',
  'readme.txt': '_info',
  readme: '_info',
  'changelog.md': '_clock',
  'changelog.txt': '_clock',
  changelog: '_clock',
  'changes.md': '_clock',
  'changes.txt': '_clock',
  changes: '_clock',
  'version.md': '_clock',
  'version.txt': '_clock',
  version: '_clock',
  mvnw: '_maven',
  'pom.xml': '_maven',
  'tsconfig.json': '_tsconfig',
  'tsconfig.node.json': '_tsconfig',
  'tsconfig.app.json': '_tsconfig',
  'tsconfig.base.json': '_tsconfig',
  'vite.config.js': '_vite',
  'vite.config.ts': '_vite',
  'vite.config.mjs': '_vite',
  'vite.config.mts': '_vite',
  'vite.config.cjs': '_vite',
  'vite.config.cts': '_vite',
  'swagger.json': '_json_1',
  'swagger.yml': '_json_1',
  'swagger.yaml': '_json_1',
  'mime.types': '_config',
  jenkinsfile: '_jenkins',
  'babel.config.js': '_babel',
  'babel.config.json': '_babel',
  'babel.config.cjs': '_babel',
  build: '_bazel',
  'build.bazel': '_bazel',
  workspace: '_bazel',
  'workspace.bazel': '_bazel',
  'bower.json': '_bower',
  'docker-healthcheck': '_docker_2',
  'eslint.config.js': '_eslint',
  'eslint.config.mjs': '_eslint',
  'eslint.config.ts': '_eslint',
  'firebase.json': '_firebase',
  geckodriver: '_firefox',
  'gruntfile.js': '_grunt',
  'gruntfile.babel.js': '_grunt',
  'gruntfile.coffee': '_grunt',
  gulpfile: '_gulp',
  'gulpfile.js': '_gulp',
  'ionic.config.json': '_ionic',
  'ionic.project': '_ionic',
  'platformio.ini': '_platformio',
  'rollup.config.js': '_rollup',
  'rollup.config.mjs': '_rollup',
  'rollup.config.ts': '_rollup',
  'sass-lint.yml': '_sass',
  'stylelint.config.js': '_stylelint',
  'stylelint.config.cjs': '_stylelint',
  'stylelint.config.mjs': '_stylelint',
  'yarn.clean': '_yarn',
  'yarn.lock': '_yarn',
  'webpack.config.js': '_webpack',
  'webpack.config.cjs': '_webpack',
  'webpack.config.mjs': '_webpack',
  'webpack.config.ts': '_webpack',
  'webpack.config.build.js': '_webpack',
  'webpack.config.build.cjs': '_webpack',
  'webpack.config.build.mjs': '_webpack',
  'webpack.config.build.ts': '_webpack',
  'webpack.common.js': '_webpack',
  'webpack.common.cjs': '_webpack',
  'webpack.common.mjs': '_webpack',
  'webpack.common.ts': '_webpack',
  'webpack.dev.js': '_webpack',
  'webpack.dev.cjs': '_webpack',
  'webpack.dev.mjs': '_webpack',
  'webpack.dev.ts': '_webpack',
  'webpack.prod.js': '_webpack',
  'webpack.prod.cjs': '_webpack',
  'webpack.prod.mjs': '_webpack',
  'webpack.prod.ts': '_webpack',
  license: '_license',
  licence: '_license',
  'license.txt': '_license',
  'licence.txt': '_license',
  'license.md': '_license',
  'licence.md': '_license',
  copying: '_license',
  'copying.txt': '_license',
  'copying.md': '_license',
  compiling: '_license_1',
  'compiling.txt': '_license_1',
  'compiling.md': '_license_1',
  contributing: '_license_2',
  'contributing.txt': '_license_2',
  'contributing.md': '_license_2',
  qmakefile: '_makefile_1',
  omakefile: '_makefile_2',
  'cmakelists.txt': '_makefile_3',
  procfile: '_heroku',
  todo: '_todo',
  'todo.txt': '_todo',
  'todo.md': '_todo',
  'npm-debug.log': '_npm_ignored',
  dockerfile: '_docker',
  'docker-compose.yml': '_docker_3',
  'docker-compose.yaml': '_docker_3',
  '.gitignore': '_git',
  '.gitattributes': '_git',
  '.gitmodules': '_git',
  '.gitconfig': '_git',
  '.npmrc': '_npm_1',
  '.nvmrc': '_config',
  '.eslintrc': '_eslint',
  '.eslintrc.js': '_eslint',
  '.eslintrc.cjs': '_eslint',
  '.eslintrc.json': '_eslint',
  '.eslintrc.yml': '_eslint',
  '.eslintrc.yaml': '_eslint',
  '.eslintignore': '_eslint_1',
  '.prettierrc': '_config',
  '.prettierrc.json': '_config',
  '.prettierignore': '_config',
  '.babelrc': '_babel',
  '.babelrc.js': '_babel',
  '.babelrc.cjs': '_babel',
  '.dockerignore': '_docker_1',
  '.env': '_config',
  '.env.local': '_config',
  '.env.development': '_config',
  '.env.production': '_config',
  '.env.test': '_config',
  'package.json': '_npm',
  'package-lock.json': '_npm',
  'pnpm-lock.yaml': '_yarn',
  'cargo.toml': '_rust',
  'cargo.lock': '_lock',
  'go.mod': '_go2',
  'go.sum': '_lock',
  gemfile: '_ruby',
  'gemfile.lock': '_lock',
  'requirements.txt': '_python',
  'setup.py': '_python',
  'pyproject.toml': '_python',
  'electron-builder.yml': '_config',
  'electron-builder.yaml': '_config',
  'vitest.config.ts': '_vite',
  'vitest.config.js': '_vite',
  makefile: '_makefile',
  'tailwind.config.js': '_config',
  'tailwind.config.ts': '_config',
  'postcss.config.js': '_config',
  'postcss.config.mjs': '_config',
  'jest.config.js': '_javascript_1',
  'jest.config.ts': '_typescript_1'
}

// ---------------------------------------------------------------------------
// Resolve filename → icon definition
// ---------------------------------------------------------------------------
function resolveIcon(name: string): IconDef {
  const lower = name.toLowerCase()

  // 1. Exact filename match
  if (NAMES[lower]) return D[NAMES[lower]] ?? D._default

  // 2. Compound extension match (e.g. "spec.ts", "css.map")
  const dotIdx = lower.indexOf('.')
  if (dotIdx !== -1) {
    const afterFirst = lower.slice(dotIdx + 1) // e.g. "spec.ts" from "foo.spec.ts"
    if (EXT[afterFirst]) return D[EXT[afterFirst]] ?? D._default

    // Try last two segments: "test.js" from "my.thing.test.js"
    const lastDot = lower.lastIndexOf('.')
    if (lastDot !== dotIdx) {
      const prevDot = lower.lastIndexOf('.', lastDot - 1)
      if (prevDot !== -1) {
        const compound = lower.slice(prevDot + 1)
        if (EXT[compound]) return D[EXT[compound]] ?? D._default
      }
    }
  }

  // 3. Simple extension
  const ext = lower.includes('.') ? lower.split('.').pop()! : undefined
  if (ext) {
    if (EXT[ext]) return D[EXT[ext]] ?? D._default
    if (LANG_EXT[ext]) return D[LANG_EXT[ext]] ?? D._default
  }

  // 4. Dotfiles without extension
  if (lower.startsWith('.')) return D._config

  return D._default
}

// ---------------------------------------------------------------------------
// React components
// ---------------------------------------------------------------------------
interface IconProps {
  size?: number
}

/** File icon rendered as a Seti font glyph */
export function FileTypeIcon({ name, size = 16 }: IconProps & { name: string }) {
  ensureFont()
  const icon = resolveIcon(name)
  return (
    <span
      className="shrink-0 leading-none"
      style={{
        fontFamily: `"${FONT_ID}"`,
        fontSize: size,
        color: icon.color,
        width: size,
        height: size,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale'
      }}
    >
      {icon.ch}
    </span>
  )
}
