name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python setuptools
        run: pip install setuptools

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format:check

      - name: Test
        run: yarn test
